<a href="https://colab.research.google.com/github/jmcquiller/NumPy-exercise-/blob/main/Copy_of_Jamiah_McQuiller_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy exercises
Authors:  Natanael Moura Junior (natanael.junior@mjv.com.br) <br>
          Carlos Eduardo Covas Costa (carlos.costa@mjv.com.br) 


<img align="center" width="200" src="https://raw.githubusercontent.com/natmourajr/data/main/mjv-tecnologia.png?raw=1">

**Question 1** -  Import the NumPy library and assign the *np* allias to it.

In [ ]:
#Type your code here
import numpy as np

**Question 2** - Create a 1D array with 10 elements (from 1 to 12) by using a list of integers.

In [ ]:
#Type your code here
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Question 3** - Create a matrix (2D array) using a **`built-in function`**. This matrix has the following characteristics: 4 rows, 3 columns and it is populated with consecutive integers from 1 to 12(including).

In [ ]:
#Type your code here
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Question 4** - Create a 4x4 ndarray by using a Built-in function that only contains consecutive even numbers from 2 to 32 (inclusive).

**Comment**: This question has a similar issue that the question 3. A good practice to solve this is to use a built-in function. For example, you can solve this by using this code:

In [ ]:
X = np.linspace(2,32,16).reshape(4,4)
print(X)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [ ]:
#Type your code here
x = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])
print(x)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


**Question 5** - reate a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array.

**Comment**: Good work! You made it a little bit forward in the question. Nice.

In [ ]:
#Type your code here
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
x = np.arange(1,26).reshape(5,5)
power = 2
answer = (x[x%2==1])**power
print(answer)
#([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25])

[  1   9  25  49  81 121 169 225 289 361 441 529 625]


In [ ]:
#Type your code here
# Use Boolean indexing to pick out only the odd numbers in the array
array = np.arange(1,26).reshape((5,5))
power = 2
answer = (array[array%2==1])**power
print(answer)

[  1   9  25  49  81 121 169 225 289 361 441 529 625]


**Question 6** - Create a 5x5 ndarray with consecutive integers from 1 to 25 (inclusive). Then, slice this 5x5 ndarray from 2nd to 3rd rows and from 2nd to last column (including) to create a new ndarray.

**Comment**: We just misunderstood a little bit the question. You can use the following code to solve this:

In [ ]:
X = np.arange(1,26).reshape(5,5)
print(X)
print('')

Y = X[1:3,1:]
print(Y)

In [ ]:
#Type your code here
# create the 5x5 ndarray
x = np.arange(1,26)
print(x)
print(x[:2])


#help

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2]


In [ ]:
#Type your code here
#create the new ndarray from X using the slice from 7th position to 15th position (including).
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(x)
print(x[7:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 8  9 10 11 12 13 14 15]


**Question 7** - Create a 1D ndarray with 10 zeros and 2x5 ndarray with zeros.

In [ ]:
#Type your code here
#1D ndarray with 10 zeros
x = np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Type your code here
#2x5 ndarray of zeros
x = np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**Question 8** - Create a 5x5 ndarray of random numbers and subtract each element by 1.

In [ ]:
#Type you code here
x = np.random.rand(5,5)-1
print(x)

[[-0.60942566 -0.99794967 -0.84099903 -0.3130314  -0.94480876]
 [-0.3438031  -0.73976065 -0.89424712 -0.08629005 -0.23460205]
 [-0.08428425 -0.08306251 -0.00958079 -0.29530616 -0.62456804]
 [-0.42306298 -0.23687175 -0.001843   -0.27113853 -0.35105957]
 [-0.31807562 -0.27200329 -0.56746393 -0.63393847 -0.22992964]]


**Question 9** -  Create a 10x10 ndarray with the constant number 5.

In [ ]:
#Type your code here
array = np.full((10,10), 5)
print(array)


[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


**Question 10** - Create an identity matrix of order 3.

**Comment**: The identity matrix is the one that has just the ones in the main diagonal. Regarding the order, saying the order of 3 is a 3x3 matrix.

In [ ]:
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Type your code here
x = np.full((5,5), 3)
print(x)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


**Question 11** - Create a vector containing 25 elements from a Normal Distribution.

In [ ]:
#Type your code here
list = [0.61734586, 0.17478441, -1.50912716, -0.33030139, 0.73613181,  0.13932753,
 -0.84172447, -0.62718555, -0.11893756,  1.22906484, -0.6102951,   0.88686249,
 -2.21570193,  0.48502811,  1.00681146, -0.22200068,  0.682334,    1.19328303,
 -1.00148646, -0.76622106, -2.25339829, -0.1084276,   0.27471227, -0.36252842,
 -0.29340567]
Vector = np.array(list)
print(Vector)

[ 0.61734586  0.17478441 -1.50912716 -0.33030139  0.73613181  0.13932753
 -0.84172447 -0.62718555 -0.11893756  1.22906484 -0.6102951   0.88686249
 -2.21570193  0.48502811  1.00681146 -0.22200068  0.682334    1.19328303
 -1.00148646 -0.76622106 -2.25339829 -0.1084276   0.27471227 -0.36252842
 -0.29340567]


**Question 12** - Create a vector containing 20 numbers equally spaced from 0 to 1.

In [ ]:
#Type your code here
x = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]]
Vector = np.array(x)
print(Vector)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]]


**Question 13** Given the matrix *`mat`*, you have to create a code to slice the matrix *`mat`* to create a submatrix that contains the 3rd,4th, and 5th rows and all columns, except the first column.

**Comment**: You can solve this part by using the following approach:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

mat[2:,1:]

In [ ]:
#Type your code here
mat = [[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]
print(mat[6: , :25])


TypeError: ignored

In [ ]:
#Type your code here

**Question 14** - Given the matrix *`mat`*, which is the indexing of number 20?

In [ ]:
#Type your code here
mat[3,4]

**Question 15** - Given the matrix *`mat`*, create a code that slices the first 3 rows of the 2nd column.

In [ ]:
#Type your code here
mat[:3,1:2]

**Question 16 A** - Given the matrix *`mat`*, create a code that slices the matrix and shows just the last line.

In [ ]:
#Type your code here
mat[4,:]

**Question 16 B** - Given the matrix *`mat`*, create a code that slices the matrix and shows the last 2 lines.

In [ ]:
#Type your code here
mat[3:5,:]

**Question 17** - Compute the overall sum of *`mat`*.

In [ ]:
#Type your code here
mat.sum()

**Question 18** - Compute the overall standard devition of *`mat`*.

In [ ]:
#Type your code here
mat.std()

**Question 19** - Compute the sum of each column of *`mat`*.

In [ ]:
#Type your code here
mat.sum(axis=0)

**Question 20** - Compute the variance of each row of *`mat`*.

In [ ]:
#Type your code here
mat.var(axis=1)

## **GREAT JOB!!!**